server:
  port: 8088
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    username: root
    password: 398653206
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&serverTimezone=GMT%2B8
logging:
  level:
    com.example.exam.dao: DEBUG
config:
  tmp-picture-path: D:/exam/tmpPicture/
  picture-path: D:/exam/picture/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
